# Generated by Django 4.2.4 on 2023-08-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApp', '0002_student_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_id',
            field=models.IntegerField(null=True),
        ),
    ]
