# Generated by Django 4.2.4 on 2023-08-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApp', '0005_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='type',
            field=models.CharField(choices=[('full', 'Full Time'), ('part', 'Part Time'), ('intern', 'Internee')], default='full', max_length=40, null=True),
        ),
    ]
