# Generated by Django 4.2.4 on 2023-09-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApp', '0008_datetime_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datetime',
            name='format',
            field=models.CharField(default='PST', max_length=30, null=True),
        ),
    ]
