# Generated by Django 4.2.4 on 2023-09-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApp', '0009_alter_datetime_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetime',
            name='status',
            field=models.CharField(default='not done', max_length=30, null=True),
        ),
    ]
