# Generated by Django 4.2.4 on 2023-09-01 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pApp', '0010_datetime_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetime',
            name='status',
        ),
    ]
