# Generated by Django 4.2.4 on 2023-09-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApp', '0011_remove_datetime_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetime',
            name='time_id',
            field=models.IntegerField(default=1),
        ),
    ]
