# Generated by Django 4.2.4 on 2023-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pApp', '0012_datetime_time_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateTimezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(default='UTC', max_length=30)),
            ],
        ),
    ]
